App_login/urls.py
from django.urls import path
from App_login import views


app_name = 'App_login'

urlpatterns = [

    path('signup/', views.sign_up, name='signup'),
    path('login/', views.Login, name='login'),
    path('logout/', views.Logout, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('change-profile/', views.user_change, name='user_change'),
    path('update_password/', views.update_password, name='update_password'), 
    path('add_propic/', views.add_propic, name='add_propic'),  
    path('change_propic/', views.change_propic, name='change_propic'),     


]

MyBlog/urls.py
from django.contrib import admin
from django.urls import path,include
from .import views

from django.conf import  settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns


urlpatterns = [
    path("admin/", admin.site.urls),
    path('account/', include('App_login.urls')),
    path('blog/', include('App_Blog.urls')),
    path('', views.Index, name ='index')

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_login/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name= 'user_profile', on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to='profile_pics')

App_login/forms.py
from django import forms
from App_login.models import UserProfile



class ProfilePic(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['profile_pic']

App_login/views.py
from django.shortcuts import render,redirect
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User,auth
from django.contrib.auth import authenticate,login,logout

from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash

from App_login.forms import ProfilePic

# Create your views here.


def sign_up(request):

    registered =False
    if request.method == 'POST':

        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        username = request.POST.get('username')
        email = request.POST.get('email')
        pass1 = request.POST.get('password1')
        pass2 = request.POST.get('password2')
        
        if pass1 != pass2:
            return HttpResponse("Password not same")
        data = User.objects.create_user(username,email,pass1)
        data.save()
        registered = True
            
    dict = {'registered': registered}
    return render(request, 'App_login/signup.html', context=dict)


def Login(request):

    Login = False
    if request.method=='POST':
        username = request.POST['username']
        password = request.POST['password']

        user=authenticate(username=username, password=password)

        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('index'))
        else:
           Login = True
    dict = {'Login': Login}
    return render(request, 'App_login/login.html', context=dict)


@login_required
def Logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))



@login_required
def profile(request):
    return render(request, 'App_login/profile.html', context={})


@login_required
def user_change(request):
    if request.method == "POST":
        username = request.POST.get('username')
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        email = request.POST.get('email')
        
        user = request.user
        user.username = username
        user.first_name = first_name
        user.last_name = last_name
        user.email = email
        user.save()
        return HttpResponseRedirect(reverse('App_login:profile'))
    else:
        return render(request, 'App_login/cngprofile.html', {'user': request.user})
        
    
@login_required  
def update_password(request):
    current_user = request.user
    changed = False
    form = PasswordChangeForm(current_user)
    if request.method =='POST':
        form = PasswordChangeForm(current_user, data=request.POST)
        if form.is_valid():
            form.save()
            changed = True

    return render(request, 'App_login/changepass.html', context={'form':form, 'changed': changed})

@login_required
def add_propic(request):
    form = ProfilePic()
    if request.method =='POST':
        form = ProfilePic(request.POST, request.FILES)
        if form.is_valid():
            user_obj = form.save(commit=False)
            user_obj.user =request.user
            user_obj.save()
            return HttpResponseRedirect(reverse('App_login:profile'))

    return render(request, 'App_login/pro_pic.html', context={'form': form})



@login_required
def change_propic(request):
    form = ProfilePic(instance = request.user.user_profile)
    if request.method == 'POST':
        form = ProfilePic(request.POST, request.FILES, instance= request.user.user_profile)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('App_login:profile'))
    return render(request, "App_login/pro_pic.html", context={'form':form})

templates/App_login/changepass.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title_block %} Profile {% endblock %}
{% block content %}

{% if changed %}
<div class="alert alert-success">
    Password Change Successfully!
</div>
{% endif %}
<form  method="POST">
    {% csrf_token %}
    {{ form | crispy }}
    <br>

    <button type="submit" class="btn btn-warning btn-sm">Change Password</button>
    
</form>

{% endblock content %}

templates/App_login/cngprofile.html
{% extends 'base.html' %}
{% block title_block %} Profile {% endblock %}


{% block content %}

<form method="POST" class="signup">
   {% csrf_token %}

    <label for="username">Username:</label>
    <input type="text" id="username" name="username" required>

    <label for="firstname">First Name:</label>
    <input type="text" id="firstname" name="first_name" required>

    <label for="lastname">Last Name:</label>
    <input type="text" id="lastname" name="last_name" required>
    
    <label for="email">Email:</label>
    <input type="email" id="email" name="email" required> <br>

    <a href="{% url 'App_login:update_password' %}">Change Password</a>
    
    <input type="submit" value="Submit" class="btn btn-success">
</form>

{% endblock content %}

templates/App_login/login.html
{% extends 'base.html' %}
{% block title_block %} Login {% endblock %}


{% block content %}

{% if Login %}
<div class="alert alert-success">
    Username or Passowrd incorrect ! <a href="{% url 'App_login:login' %}">Try Agian </a>
</div>
{% else %}   

<h2>Login: </h2>



<form method="POST" class="signup">

    {% csrf_token %}

    <label for="username">Username:</label>
    <input type="text" id="username" name="username" required>
    
    <label for="psw">Password:</label>
    <input type="password" id="psw" name="password" required> <br>

    <!-- <label for="psw_reapt">Repeat Password:</label>
    <input type="password" id="psw_repeat" name="password2" required> <br> -->
    
    <input type="submit" value="Login" class="btn btn-success">
</form>
<br>

<p>Create an Account! <a href="{% url 'App_login:signup' %}">SignUp </a> </p>




{% endif %}
{% endblock content %}

templates/App_login/pro_pic.html
{% extends 'base.html' %}
{% block title_block %} Profile {% endblock %}


{% block content %}

<h2>Add Your Profile pic </h2>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}

    <button type="submit" class="btn btn-success btn-sm">Add</button>

</form>

{% endblock content %}

templates/App_login/profile.html
{% extends 'base.html' %}
{% block title_block %} Profile {% endblock %}


{% block content %}

<h2>Your Profile </h2>
{% if user.user_profile  %}

<img src="/media/{{user.user_profile.profile_pic}}" class="rounded-circle" width="100px" height="100px">
<br> <br>
<a href="{% url 'App_login:change_propic' %}" class="btn btn-info btn-sm">Change profile pics</a>

{% else %}
<img src="/media/profile_pics/user.png"  class="rounded-circle" width="100px"> <br> <br>
<a href="{% url 'App_login:add_propic' %}" class="btn btn-info btn-sm">Change profile pics</a>

{% endif %}
<hr>
<p>Username: {{user.username }} </p>
<p>Email: {{user.email}} </p>
<p>Name: {{user.first_name}} {{user.last_name}} </p>


<a href="{% url 'App_login:user_change'  %}" class="btn btn-warning btn-sm">Change Profile</a>

{% endblock content %}

templates/App_login/signup.html
{% extends 'base.html' %}
{% block title_block %} Create New Account {% endblock %}


{% block content %}

{% if registered %}
<div class="alert alert-success">
    Account Created Successfully ! <a href="{% url 'App_login:login' %}">Login Here </a>
</div>

{% endif %}
<h2>Create New Account: </h2>

<form method="POST" class="signup">
    {% csrf_token %}
     

    <label for="firstname">First Name:</label>
    <input type="text" id="firstname" name="first_name" required>

        
    <label for="lastname">Last Name:</label>
    <input type="text" id="lastname" name="last_name" required>

    <label for="username">Username:</label>
    <input type="text" id="username" name="username" required>
    
    <label for="email">Email:</label>
    <input type="email" id="email" name="email" required>

    <label for="password1">Password:</label>
    <input type="password" id="password1" name="password1" required> 

    <label for="password2">Confrom Password:</label>
    <input type="password" id="password2" name="password2" required> <br>
    <!-- <label for="psw_reapt">Repeat Password:</label>
    <input type="password" id="psw_repeat" name="password2" required> <br> -->
    
    <input type="submit" value="Submit" class="btn btn-success">
</form>
<br>

<p>Already have an account? <a href="{% url 'App_login:login' %}">Login</a> </p>


{% endblock content %}